server:
  port: 8080
spring:
  datasource:
    username: root
    password: Kivin625bugr
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
    - url: https://comunello.msk.ru
      name: Comunello.MSK
indexing-errors:
  errors:
    - name: indexing_in_progress
      message: Индексация уже запущена
    - name: indexing_not_started
      message: Индексация не запущена
parser-settings:
  user-agent: HeliontSearchBot
  referrer: https://www.google.com
  get-parameters: ?#%